name: Publish package

on:
  push:
    branches:
    - main

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    with:
      skip-existing: true
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Install hatch
      run: pip install -U hatch
    - name: Build
      run: hatch build
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
